# Generated by Django 4.0 on 2022-02-10 10:50

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_image_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('year', models.IntegerField()),
                ('type_body', models.CharField(max_length=300, verbose_name='kuzov')),
                ('number_place', models.IntegerField()),
                ('number_door', models.IntegerField()),
                ('power_motor', models.CharField(max_length=250)),
                ('power_battery', models.FloatField()),
                ('power_reserve', models.IntegerField(verbose_name='quvvat_zahirasi')),
                ('max_speed', models.IntegerField()),
                ('acceleration', models.FloatField(verbose_name='tezlanish')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('brend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.brend')),
                ('color', models.ManyToManyField(blank=True, to='mainapp.Color')),
            ],
        ),
    ]
