# Generated by Django 4.0 on 2022-02-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_postimage_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='video',
            field=models.FileField(blank=True, upload_to='car/videos'),
        ),
    ]
