# Generated by Django 4.0 on 2022-02-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_postimage_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='CarImage',
        ),
    ]
