# Generated by Django 4.0 on 2022-02-11 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_postimage_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='mainapp.brend'),
        ),
    ]
