# Generated by Django 4.0 on 2022-03-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_carimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='mainapp.brend'),
        ),
    ]
