# Generated by Django 4.0 on 2022-03-07 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_car_acceleration_alter_car_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='mainapp.car'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='car/videos'),
        ),
    ]
