# Generated by Django 4.0 on 2022-03-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_car_acceleration_alter_car_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='images',
        ),
    ]
