# Generated by Django 4.0 on 2022-03-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_remove_car_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
