# Generated by Django 4.0 on 2022-03-08 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_brend_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='mainapp.brend'),
        ),
    ]
